include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Jobs/Build.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
- lint
- build
- test

checkbashisms:
  image: alpine:latest
  stage: lint
  before_script:
    - apk add checkbashisms
  script:
    - find ./ -type f -name "*.sh" -exec checkbashisms -f {} \;

shellcheck:
  image: koalaman/shellcheck-alpine:stable
  stage: lint
  before_script:
    - shellcheck --version
  script:
    - find ./ -type f -name "*.sh" -exec shellcheck {} \;
  allow_failure: true

shfmt:
  image: mvdan/shfmt:latest-alpine
  stage: lint
  before_script:
    - shfmt -version
  script:
    - shfmt -i 2 -ci -d .

test_build:
  variables:
    DOCKER_HOST: tcp://docker:2375
  stage: test
  image: docker
  services:
  - docker:dind
  needs:
    - job: build
  before_script:
    - docker info
  script:
    - |
      tests/simple-image/build_image.sh -i "$CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG"
      ls -lahR tests/simple-image/cache
      ls -lahR tests/simple-image/output
