include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - local: resources/CI/lint.yml
  - local: resources/CI/buildx.yml
  
stages:
- lint
- build
- test

test_build:
  variables:
    DOCKER_HOST: tcp://docker:2375
  stage: test
  image: docker
  services:
    - docker:dind
  needs:
    - job: build
  before_script:
    - docker info
  script:
    - |
      tests/simple-image/build_image.sh -i "$CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG"
      ls -lahR tests/simple-image/cache
      ls -lahR tests/simple-image/output
