include:
  - template: Code-Quality.gitlab-ci.yml  
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Build.gitlab-ci.yml
  - project: container-email/resources/gitlab-templates
    ref: main
    file: shellcheck.yml

stages:
- lint
- build
- test

shellcheck:
  allow_failure: true

test_build:
  variables:
    DOCKER_HOST: tcp://docker:2375
  stage: test
  image: docker
  services:
  - docker:dind
  needs:
    - job: build
  before_script:
    - docker info
  script:
    - |
      cd tests/simple-image || exit 1
      ./build_image.sh
      ls -lahR ./output
