on:
  push

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run Docker Container
        run: |
          docker run --rm -v $PWD/output:/output ghcr.io/raspi-alpine/builder
