on:
  push

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: kismetwireless/kismet
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential git libwebsockets-dev pkg-config \
            zlib1g-dev libnl-3-dev libnl-genl-3-dev libcap-dev libpcap-dev git \
            libnm-dev libdw-dev libsqlite3-dev libprotobuf-dev libprotobuf-c-dev \
            protobuf-compiler protobuf-c-compiler libsensors-dev libusb-1.0-0-dev \
            python3 python3-setuptools python3-protobuf python3-requests binutils-aarch64-linux-gnu \
            python3-numpy python3-serial python3-usb python3-dev python3-websockets \
            librtlsdr-dev libubertooth-dev libbtbb-dev libmosquitto-dev gcc make gcc-aarch64-linux-gnu
      - name: Compile kismet
        run: |
          pwd
