name: 'docker'

on:
  push:
    branches:
      - master

jobs:
  skip_ci:
    runs-on: ubuntu-latest
    # Map the job output to 'skip'
    outputs:
      skip: ${{ steps.check_skip.outputs.result }}
    steps:
      - name: Check For Skip
        id: check_skip
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            let res = 'run';
            const commits = ${{ toJSON(github.event.commits) }};
            for (const commit of commits) {
              console.log( commit );
              if (commit.message.includes("[skip actions]") || commit.message.includes("[skip ci]")) {
                res = 'skip';
              }
            }
            return res;

  docker:
    # Wait for the skip_ci job to run
    needs: skip_ci
    # And only run the build if canSkip isn't 'true'.
    if: ${{ needs.skip_ci.outputs.skip != 'skip' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Docker label info
        id: docklabel
        run: |
          echo "::set-output name=ref::$GITHUB_REF_NAME"
          echo "::set-output name=sha::$GITHUB_SHA"
          echo "::set-output name=repo::$GITHUB_REPOSITORY"
          echo "::set-output name=timestamp::$(date '+%Y%m%d_%H%M%S')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ghcr.io/${{ steps.docklabel.outputs.repo }}:${{ steps.docklabel.outputs.timestamp }}
            ghcr.io/${{ steps.docklabel.outputs.repo }}
          labels: |
            org.opencontainers.image.revision=${{ steps.docklabel.outputs.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
