name: 'docker'

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Timestamp
        run: echo "timestamp=$(date '+%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/bboehmke/raspi-alpine-builder:${{env.timestamp}}
            ghcr.io/bboehmke/raspi-alpine-builder:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
